services:
  currency-exchange:
    image: pratyushud/exchange-service:0.0.1-RELEASE
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://host.docker.internal:2200/exchange?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/

  currency-converter:
    image: pratyushud/conversion-service:0.0.1-RELEASE
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/

  gateway-server:
    image: pratyushud/gateway-service:0.0.1-RELEASE
    ports:
      - "8765:8765"
    networks:
      - currency-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/

  naming-server:
    image: pratyushud/naming-service:0.0.1-RELEASE
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.8
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: